/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f407.h"
#include"gpio.h"
#include"spi.h"
#include<string.h>
#include"uart.h"
#include"i2c.h"
#include"otg.h"
#include"timer.h"
#include"math.h"
////khai bao usb cdc-----------------------------------/////////////
OTG_FS_ConFig_t g;
uint32_t packet[64];
USB_SETUP_PACKET op,pp;
uint8_t mode,pktsts=0,count=0,count1=0;
uint16_t bcnt=0,addr,addr1;
char bufer[11];
uint8_t set_line[7];
uint8_t receive[64];
uint8_t key=0,rei=0;
///////////////////////////////////
TIM_Handle_t tim1,tim2;
int dem=0,count2=0,count3=0,count4=0,count5=0;
int16_t pi=0,hi=0,pi_last=0,befor=0,befor1=0,servo_last=2499,servo_cur=2499;
uint8_t flag1=0,flag2=0,flag4=0;
void USB_CDC_init()
{
	    *((__vo uint32_t*)(0x40023C00))&=~(0x7);
		*((__vo uint32_t*)(0x40023C00))|=3;//60-90 mhz for hclk
		//enable hse
		RCC->CR|=1<<16;
		while(!(RCC->CR&(1<<17)));

		//choose PLL entry
		RCC->PLLCFGR|=1<<22;
		//PLL div M
		RCC->PLLCFGR&=~(0x3f);
		RCC->PLLCFGR|=8;//1mhz
		//PLL mul N
		RCC->PLLCFGR&=~(0x1ff<<6);
		RCC->PLLCFGR|=288<<6;//288mhz

		//PLL div q for otg fs 48mhz
		RCC->PLLCFGR&=~(0xf<<24);
		RCC->PLLCFGR|=6<<24;//48mhz
		//PLL div P for sys clock

		RCC->PLLCFGR&=~(0x3<<16);
		RCC->PLLCFGR|=0<<16;//144mhz
		// enable pll
		RCC->CR|=1<<24;
		while(!(RCC->CR&(1<<25)));
		//system clock select
		RCC->CFGR&=~(0x03);
		RCC->CFGR|=2;//pll selected as system clock
		while(((RCC->CFGR>>2)&0x03)!=0x02);//wait system clock sta en pll
		//AHB PRE
		RCC->CFGR&=~(0xf<<4);
		RCC->CFGR|=8<<4;//72mhz
		//APB2
		RCC->CFGR&=~(0x7<<13);
		RCC->CFGR|=4<<13;//36mhz
		//APB1
		RCC->CFGR&=~(0x7<<10);
		RCC->CFGR|=4<<10;//36mhz

		GPIO_Handle_t x;
		x.gpiox=GPIOA;
		x.gpioy.mode= GPIO_ALTFUNC;
		x.gpioy.optype=GPIO_OUTPUT_PP;
		x.gpioy.ospeed=GPIO_VRY_HIGH_SPEED;
		x.gpioy.pin=GPIO_PIN_8;
		x.gpioy.alt_num=GPIO_PIN_AF10;
		//x.gpioy.pupd=GPIO_PU;
		GPIO_Init(&x);
		x.gpioy.pin=GPIO_PIN_9;
		GPIO_Init(&x);
		x.gpioy.pin=GPIO_PIN_10;
		GPIO_Init(&x);
		x.gpioy.pin=GPIO_PIN_11;
		GPIO_Init(&x);
		x.gpioy.pin=GPIO_PIN_12;
		GPIO_Init(&x);
		g.Global= OTG_GLOBAL;
		g.Host=OTG_HOST;
		g.Device=OTG_DEVICE;
		g.PCGCCTL=OTG_POWER;
		OTG_FS_Core_Init(&g);
		OTG_FS_Device_Init(&g);
}
static inline void FPU_Enable(void)
{
    FPU_CPACR |= (0xF << 20);
    __asm volatile ("dsb 0xF");
    __asm volatile ("isb 0xF");
    FPU->FPCCR |= (1 << 31);   // ASPEN
    FPU->FPCCR |= (1 << 30);   // LSPEN
}
void TIM1_init()
{
	tim1.timx=TIM1;
	tim1.timy.mode=0;
	tim1.timy.ARR_control=TIM_ARR_DI;
	tim1.timy.DIR_control=TIM_UPCNT;
	tim1.timy.one_pulse=TIM_ONE_PULSE_DI;
	tim1.timy.psc=71; //10us
	TIM_Init(&tim1);
	TIM1->DIER|=1;
	TIM1->CR1|=1;
	NVIC_ConFig(25,ENABLE);
	NVIC_PRIORITY(25,1);
}
void TIM2_init()
{
	tim2.timx=TIM2;
	tim2.timy.mode=0;
	tim2.timy.ARR_control=TIM_ARR_EN;
	tim2.timy.DIR_control=TIM_UPCNT;
	tim2.timy.one_pulse=TIM_ONE_PULSE_DI;
	tim2.timy.psc=71; //1us
	TIM_Init(&tim2);
}
void TIM2_PWM()
{
	GPIO_Handle_t y;
	y.gpiox=GPIOB;
	y.gpioy.mode=GPIO_ALTFUNC ;
	y.gpioy.optype=GPIO_OUTPUT_PP;
	y.gpioy.pin=GPIO_PIN_10;
	y.gpioy.ospeed=GPIO_VRY_HIGH_SPEED;
	y.gpioy.alt_num=GPIO_PIN_AF1;
	GPIO_Init(&y);

	TIM2->ARR=19995;
	TIM2->CCMR[1]&=~(0x07<<4);
	TIM2->CCMR[0]&=~(0x07<<12);
	//TIM2->CCMR[0]|=(0x06<<12);//pWM mode for channel 2
	TIM2->CCMR[1]|=(0x06<<4);//pWM mode for channel 3

	TIM2->CCMR[0]|=(1<<11);
	TIM2->CCMR[1]|=(1<<3);
	TIM2->CCER|=1<<8|1<<4;
	TIM2->CCR[2]=999;//ccr3
	//TIM2->CCR[1]=699;//ccr2
	TIM2->CR1|=1<<7;
	TIM2->EGR|=1;

	TIM2->CR1|=1;
//	y.gpioy.gpio_pin=GPIO_PIN_3;
//	GPIO_Init(&y);
}
void control_step(uint8_t dir,uint8_t step,uint8_t en,uint8_t pin1,uint8_t pin2,uint8_t pin3)
{
	GPIO_WritePin(GPIOD,pin1,dir);
	GPIO_WritePin(GPIOD,pin3,en);
	for(int i=0;i<step*2;i++)
	{
		GPIO_TogglePin(GPIOD,pin2);
		for(int k=0;k<2000;k++);
	}
}
void control_step_x_y(uint8_t dir,uint8_t step,uint8_t en,uint8_t pin1,uint8_t pin2,uint8_t pin3,uint8_t dir1,uint8_t step1,uint8_t en1,uint8_t pin4,uint8_t pin5,uint8_t pin6)
{
	GPIO_WritePin(GPIOD,pin1,dir);
	GPIO_WritePin(GPIOD,pin3,en);
	GPIO_WritePin(GPIOD,pin4,dir1);
	GPIO_WritePin(GPIOD,pin6,en1);
	uint8_t stepx=step;
	if(step>step1) stepx=step1;
	for(int i=0;i<stepx*2;i++)
	{
		GPIO_TogglePin(GPIOD,pin2);
		GPIO_TogglePin(GPIOD,pin5);
		for(int k=0;k<2000;k++);
	}
	if(step<=step1)
	{
	for(int i=0;i<(step1-stepx)*2;i++)
	{
		GPIO_TogglePin(GPIOD,pin5);
		for(int k=0;k<2000;k++);
	}
	}
	else if(step1<step)
	{
		for(int i=0;i<(step-stepx)*2;i++)
		{
			GPIO_TogglePin(GPIOD,pin2);
			for(int k=0;k<2000;k++);
		}
	}
}
void usb_reiceive_handle(uint8_t *received)
{
	if(rei==2)
	{
	   pi=(int16_t)((received[1])<<8)|received[0];
	   hi=(int16_t)((received[3])<<8)|received[2];
	   int16_t hu=(int16_t)((received[5])<<8)|received[4];
	   int16_t row=(int16_t)pi-befor;
	   int16_t col=(int16_t)hi-befor1;
	   if(hu==0x00)
	   {
		   TIM2->CCR[2]=2499;
		   servo_cur=2499;
		   //for(int i=0;i<1000;i++);
	   }
	   else if(hu==0x01)
	   {
		   TIM2->CCR[2]=999;//ccr3
		   servo_cur=999;
		   //for(int i=0;i<1000;i++);
	   }
	   if(servo_cur!=servo_last)
	   {
		   count5++;
		   if(count5>=350)
		   {
			   servo_last=servo_cur;
			   flag4=1;
			}
	   }
	   else if(servo_cur==servo_last)flag4=1;
	   if(flag4==1)
	   {
		//if(row!=0)
		if(count2<abs(row) && count3<abs(col))
		{
			if(row>=0 && col>=0) control_step_x_y(0,1,0,8,9,13,0,1,0,12,11,10);
			else if(row<0 && col>=0) control_step_x_y(1,1,0,8,9,13,0,1,0,12,11,10);
			else if(row>=0 && col<0) control_step_x_y(0,1,0,8,9,13,1,1,0,12,11,10);
			else if(row<0 && col<0) control_step_x_y(1,1,0,8,9,13,1,1,0,12,11,10);
			count2++;count3++;
		}
		else if(count2<abs(row) && count3>=abs(col))
		{
			if(row>=0) control_step_x_y(0,1,0,8,9,13,0,0,0,12,11,10);
			else control_step_x_y(1,1,0,8,9,13,0,0,0,12,11,10);
			count2++;
			flag2=1;
		}
		else if(count3<abs(col) && count2>=abs(row))
		{
			if(col>=0) control_step_x_y(0,0,0,8,9,13,0,1,0,12,11,10);
			else control_step_x_y(0,0,0,8,9,13,1,1,0,12,11,10);
			count3++;
			flag1=1;
		}
		else if(count3>=abs(col) && count2>=abs(row))
		{
			control_step_x_y(0,0,0,8,9,13,0,0,0,12,11,10);
			flag1=1;flag2=1;
		}
/*		if(count2<abs(row))
		{
		count2++;
		//usb_reiceive_handle(receive);
		 if(row>=0)
	     control_step(0,1,0,8,9,13);
		 else control_step(1,1,0,8,9,13);
		}
		else
		{
			control_step(0,0,0,8,9,13);
			flag1=1;
		}
		//if(col!=0)
		if(count3<abs(col))
		{
		 count3++;
		 if(col>=0)
	     control_step(0,1,0,12,11,10);
		 else control_step(1,1,0,12,11,10);
		}
		else
		{
			control_step(0,0,0,12,11,10);
			flag2=1;
		}*/
		if(flag1==1 && flag2==1)
		{
			CDC_SendData(&g,(uint8_t*)("ok\n"),3);
			  for(int i=0;i<6;i++)
			   {
				   received[i]=0x0;
			   }
			flag1=0;count2=0;
			flag2=0;count3=0;
			befor=pi;
			befor1=hi;
			count4++;
			count5=0;
			flag4=0;
			rei=0;
		}
	   }
	}
}
void gpio_init()
{
	GPIO_Handle_t x;
	x.gpiox=GPIOD;
	x.gpioy.mode=GPIO_OUTPUT;
	x.gpioy.optype=GPIO_OUTPUT_PP;
	x.gpioy.ospeed=GPIO_VRY_HIGH_SPEED;
	x.gpioy.alt_num=GPIO_PIN_AF0;
	x.gpioy.pin=GPIO_PIN_8;
	x.gpioy.pupd=GPIO_PU;
	GPIO_Init(&x);
	x.gpioy.pin=GPIO_PIN_9;
	GPIO_Init(&x);
	x.gpioy.pin=GPIO_PIN_13;
	GPIO_Init(&x);
	x.gpioy.pin=GPIO_PIN_12;
	GPIO_Init(&x);
	x.gpioy.pin=GPIO_PIN_11;
	GPIO_Init(&x);
	x.gpioy.pin=GPIO_PIN_10;
	GPIO_Init(&x);
	x.gpiox=GPIOB;
	x.gpioy.pin=GPIO_PIN_9 ;
	GPIO_Init(&x);
}
int main(void)
{
  	FPU_Enable();
	USB_CDC_init();
	 gpio_init();
	 TIM2_init();
	 TIM2_PWM();
	 TIM1_init();
    /* Loop forever */
	while(1)
	{
	}
}
void OTG_FS_IRQHandler ()
{
	OTG_IRQ_Handle(&g);
}
void TIM1_UP_TIM10_IRQHandler ()
{
	if(key==1)
	{
		//if(dem>=100)
		{
		usb_reiceive_handle(receive);
		//if(flag4=0)
		//count5++;
		//control_step(0,100,0,8,9,13);
		dem=0;
		}
		//else dem++;
	}
	GPIO_TogglePin(GPIOB,GPIO_PIN_9);
	TIM_IRQ_Handle(&tim1);
}
